site_name: Change me
site_description: Temp
site_url: https://localhost
theme:
    name: material
repo_name: joecstarr/changeme
repo_url: https://github.com/joecstarr/changeme
extra_css:
  - 'https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0/katex.min.css'

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0/katex.min.js'
  - 'extra.js'

plugins:
    search: null
    redirects:
        redirect_maps:
    # mkdocstrings:
    #   handlers:
    #     python:
    #       options:
    #         extensions:
    #         - griffe_typingdoc
    #         show_root_heading: true
    #         show_if_no_docstring: true
    #         preload_modules:
    #         - httpx
    #         - starlette
    #         inherited_members: true
    #         members_order: source
    #         separate_signature: true
    #         unwrap_annotated: true
    #         filters:
    #         - '!^_'
    #         merge_init_into_class: true
    #         docstring_section_style: spacy
    #         signature_crossrefs: true
    #         show_symbol_type_heading: true
    #         show_symbol_type_toc: true
nav:
    - Home: README.md
    - Use Cases: use_cases/index.md
    - Unit Descriptions: unit_descriptions/index.md
markdown_extensions:
    abbr: null
    attr_list: null
    footnotes: null
    md_in_html: null
    tables: null
    toc:
        permalink: true
    pymdownx.arithmatex:
      generic: true
    pymdownx.betterem: null
    pymdownx.caret: null
    pymdownx.highlight:
        line_spans: __span
    pymdownx.inlinehilite: null
    pymdownx.keys: null
    pymdownx.mark: null
    pymdownx.superfences:
        custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:pymdownx.superfences.fence_code_format ""
    pymdownx.tilde: null
    pymdownx.blocks.admonition:
        types:
            - note
            - attention
            - caution
            - danger
            - error
            - tip
            - hint
            - warning
            - info
            - check
    pymdownx.blocks.details: null
    pymdownx.blocks.tab:
        alternate_style: true
    mdx_include: null
    markdown_include_variants: null
extra:
    social:
        - icon: fontawesome/brands/github-alt
          link: https://github.com/joecstarr/changeme
